/* ==========================================================================
   ATHA — sitemap generator
   Reads the content manifests and rewrites sitemap.xml so published guides
   and meditations are always indexed without hand-editing anything.

   Run from the site root:  node tools/build-sitemap.mjs
   Draft entries are skipped — publishing is a manifest status change.
   ========================================================================== */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SITE = 'https://guledaaydemir.github.io/atha/';
const TODAY = new Date().toISOString().slice(0, 10);

const STATIC_PAGES = [
  { path: '',                    changefreq: 'weekly',  priority: '1.0' },
  { path: 'features/',           changefreq: 'monthly', priority: '0.9' },
  { path: 'guides/',             changefreq: 'weekly',  priority: '0.9' },
  { path: 'meditations/',        changefreq: 'weekly',  priority: '0.9' },
  { path: 'press/',              changefreq: 'monthly', priority: '0.6' },
  { path: 'apps/',               changefreq: 'monthly', priority: '0.6' },
  { path: 'about.html',          changefreq: 'monthly', priority: '0.7' },
  { path: 'support.html',        changefreq: 'monthly', priority: '0.7' },
  { path: 'privacypolicy.html',  changefreq: 'yearly',  priority: '0.4' },
  { path: 'terms.html',          changefreq: 'yearly',  priority: '0.4' }
];

const COLLECTIONS = [
  { file: 'content/guides.json',      changefreq: 'monthly', priority: '0.8' },
  { file: 'content/meditations.json', changefreq: 'monthly', priority: '0.8' }
];

function escapeXML(value) {
  return String(value)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&apos;');
}

function entry({ loc, lastmod, changefreq, priority }) {
  return [
    '  <url>',
    `    <loc>${escapeXML(loc)}</loc>`,
    `    <lastmod>${lastmod}</lastmod>`,
    `    <changefreq>${changefreq}</changefreq>`,
    `    <priority>${priority}</priority>`,
    '  </url>'
  ].join('\n');
}

async function readManifest(relativePath) {
  try {
    return JSON.parse(await readFile(join(ROOT, relativePath), 'utf8'));
  } catch (error) {
    console.warn(`skipped ${relativePath}: ${error.message}`);
    return null;
  }
}

async function build() {
  const urls = STATIC_PAGES.map((page) =>
    entry({ loc: SITE + page.path, lastmod: TODAY, changefreq: page.changefreq, priority: page.priority })
  );

  let published = 0;
  let drafts = 0;

  for (const collection of COLLECTIONS) {
    const manifest = await readManifest(collection.file);
    if (!manifest || !Array.isArray(manifest.items)) { continue; }

    const base = manifest.basePath ?? '';

    for (const item of manifest.items) {
      // Only published, self-hosted pages belong in the sitemap.
      if (item.status === 'draft' || item.status === 'hidden') { drafts++; continue; }
      if (item.external || (item.href && /^https?:/.test(item.href))) { continue; }
      if (!item.slug) { continue; }

      published++;
      urls.push(entry({
        loc: `${SITE}${base}${item.slug}.html`,
        lastmod: item.updated || TODAY,
        changefreq: collection.changefreq,
        priority: item.featured ? '0.85' : collection.priority
      }));
    }
  }

  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!--',
    '  Generated by tools/build-sitemap.mjs from the content manifests.',
    '  Do not hand-edit: run `node tools/build-sitemap.mjs` after adding content.',
    '-->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    urls.join('\n'),
    '</urlset>',
    ''
  ].join('\n');

  await writeFile(join(ROOT, 'sitemap.xml'), xml, 'utf8');
  console.log(`sitemap.xml written — ${urls.length} URLs (${published} from manifests, ${drafts} drafts skipped)`);
}

build().catch((error) => {
  console.error(error);
  process.exit(1);
});